version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/angularclient"
    schedule:
      interval: "weekly"
      time: "04:00"
    open-pull-requests-limit: 5
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 5